
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# Miscelaneous
favicon: /images/favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/my_theme.css

# scripts loaded in the end of the body
scripts:
- /js/jquery.min.js
- /js/my_theme.js

# highlight theme
highlight_theme: vs2015